### ISSUE TITLE
Search fields not returning expected results

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#144] opened 2014-07-09 23:36 UTC
**[Search Schools](http://beta.ccctransfer.org/school-search)**
Searching for "California Baptist University" under the Search School returns null. Even searching by 'California' is not returning the correct number of California schools. Are the schools' states mis-tagged? 

Now just search by 'California'
Search results:
1.   Southern **Oregon** University
Accelerated Degrees California Student Page SOU Residency Requirements Transfer ... Scholarship Program GE Transfer Guide to SOU California SOU Exchange Program Campus type ...
1.   **Arizona** State University
   ... Guidelines Undergraduate G.E. Requirements for California Transfers WUE Approved Programs for Reduced Tuition ...
2.   Portland State University
   Admission for California Student Transfers Advising Diversity at PSU ...
3.   University of **Colorado**, Colorado Springs
   Apply Now California Transfer Students Housing Scholarships ...
4.   Maryville University, Missouri
   ... Programs Admission Requirements $5,000 California Grant Free Online Application Scholarships ...
5.   UC Santa Barbara
   ... Street address 1210 Cheadle Hall University of California City Santa Barbara Zip code 93106 ...

Ruth says 

> It should have shown me 4 campuses as well (and who knows what else that it may have missed): California Baptist University, California College of the Arts, California Institute of the Arts and California Lutheran 
> 
> I wondered if this search bar was a copy of the search bar at the top of all the TCW pages that searches TCW website – so I did a little more testing and found that both the search bar inserted in the search school filter page AND the search bar on top of each TCW page are _not_ finding all content in the TCW – for example, _neither_ search bar found the following:
> - Alliant International University
> - American Jewish University
> - Art Center College of Design
> - Azusa Pacific University
> - Biola University
> - Brandman University 
> - California Baptist University 
> - California College of the Arts 
> - California Institute of the Arts 
> - California Lutheran University 
> - Chapman University ( when I entered Chapman in the upper search bar on the TCW pages it gave me all Brandman results – but not the campus titled Chapman University (hmmm….) … etc…

Correct me if I am wrong – but this seems to indicate that BOTH search bar do not work properly.

**Comment by bodhiprice** [comment] 2014-07-10 00:18
OK, several things going on here. First, search doesn't target only the title field. The body is also searched and all the results above had California in the body field. This is expected behavior. On the other hand, most of the California schools are, for example, UC Davis, UC Los Angeles, etc. No mention of California. So, fix that and the problem gets smaller.

Regarding the schools that are missing from the results. It looks like they were all AICCU schools. The search block intentionally wasn't configured to search those - they only consist of a PDF and I thought of them as sort of a 'utility' content type used in views - but I've corrected that.

I've also set the site to re-index the content. This will take some time. 

One BIG thing to watch for with search - requests for functionality not provided by an existing Drupal module should be approached with caution - could be considerable work depending on the request.

**Comment by bodhiprice** [comment] 2014-07-10 00:41
@wdg-thomas I've been working on this and I'm seeing an issue with indexing of the AICCU schools. Let me have some time in the morning before you get back to her or have anyone touch the site. I'd like to try a different config on the beta install, but may have to roll it back.

**Comment by bodhiprice** [comment] 2014-07-10 13:47
@wdg-thomas @hmickelson I have the AICCU thing sorted out and you can edit content again. I think the California issue will be resolved by fixing school names.

**Comment by ghost** [comment] 2014-07-10 21:33
@friendlymachine 
Soooo, searching by, say, 'UC' should return the UC campuses, but it doesn't. 
Can we just limit the search field to search only the campus name as the label implies rather than just conent? 

![screen shot 2014-07-10 at 2 31 44 pm](https://cloud.githubusercontent.com/assets/7529130/3545688/c4572e4e-0879-11e4-935b-0772e2c9d449.png)

**Comment by bodhiprice** [comment] 2014-07-11 00:19
@wdg-thomas This is because a minimum word length is set - three characters, so UC doesn't make the cut. This can be changed, but if the request is to rebuild search, I will do it. But I'll need everyone else (including Ruth) to stay off the beta site while I'm doing that work. It's also a rebuild - not a tweak or reconfig. It will be an entirely different solution. The current solution simply doesn't have this functionality.

**Comment by ghost** [comment] 2014-07-11 18:30
I'm putting the cart before the horse for a minute, but if Ruth & Ray can see the benefit—and addressing her first issue, that of seeing school in "California"—I would propose: 
1. Killing off the Search block :hammer: 
2. Add "California" back into the Filter—which solves her immediate problem
3. Extending the Filter block down the right column to show more states to keep her older user base from having to scroll. I mean, they're aren't mobile users anyway. 

_Impact:_
_Development_: Just time removing Search block and extending Filter
_Cost_: Time spent on dev, QA, and PM

Again, this depends on what they would say. I have _not_ sent this to the client yet. 

![school-search-filter](https://cloud.githubusercontent.com/assets/7529130/3556721/70232ba8-0927-11e4-86bb-0f9eebe14da2.png)

**Comment by ghost** [comment] 2014-07-16 00:24
Enabled "California". Client happy. Functional as desired.

**Closed as completed** 2014-07-16 00:25 UTC
Labels: bug, development
