### ISSUE TITLE
TCW Assessment table needs rearranging in following order: CC, CSU, UC OOS

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#185] opened 2014-10-29 21:18 UTC
This was previously requested, which was completed in the in-page menu but the tables were not rearranged.  Please rearrange tables on the page to match the following order:
CC | CSU | UC | OOS

**Comment by mlwoodward** [comment] 2014-11-14 07:58
Figured out the issue.  Still working on a fix.  The issue is that the alphabetical listing of schools separated by campus type is overriding the order of taxonomy (campus type).  If you look at the first school for each campus type you will notice that they will list in alphabetical order.  Example based on current results.  Listing are showing first campus for each campus type:

CC: Alameda College
OOS: Azusa Pacific
CSU: Cal Maritime
UC: UC Berkeley

Basically the double filter of Campus type and Campus Name are conflicting.  

Note for self: To update / patch based on current tests...add Relationship Term to the view, then add related term to fields, finally add filter to table.  Will need to try a few other combinations to work out the double filter issue.

---

Note to Ruth of partial success:  I was able to get the sections listed both alphabetically by campus name and by campus type.  Basically the sections are now in the following order: CC, CSU, OOS, UC.  In each section the list is then alphabetical by campus name.  Working on a possible last solution on this.

**Comment by mlwoodward** [comment] 2014-11-14 08:19
Was able to fix the filtration of the section to fix both issues.  I am now closing this issue.

**Comment by mlwoodward** [comment] 2015-01-14 19:52
Note - remove all sorts and it works fine.

**Closed as completed by mlwoodward** 2015-01-14 19:52 UTC

**Comment by Ruth-DeTro** [comment] 2015-01-14 19:59
Hi Michael,

I looked at this issue in the GitHub site and think it is great that you could figure this out!  Issue # 185 is now at rest.  Thank you.:-)

Ruth D.
