### ISSUE TITLE
Search Schools: Change search to ANY type

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#169] opened 2014-08-04 23:10 UTC
> 1. The search box is still too constraining and not showing all results properly. Must be more flexible.
>    E.g. search word: ART provides two schools ( Art Center College of Design & Otis College of Art & Design), there are more than two schools with the word ART in the title: does not pick up California College of Arts and California Institute of the Arts. Search on ARTS and you get the opposite problem as described here.

**Comment by bodhiprice** [comment] 2014-08-04 23:23
This is a bit vague. Is this a "fix by any means necessary" kind of a thing? Could get out of hand. Drupal search != Google search.

**Comment by Ruth-DeTro** [comment] 2014-11-13 22:55
Still need this issue on campus search bar - need it to be able to type three characters and show a results with all campuses whose name contains those three characters.  I.E. If user types the three characters, "ART" , the results should include three campuses found - not two.  
If user types "CAL" the results should include 7 AICCU and 2 CSU campuses - not  just 2 AICCUs and 2 CSUs.

**Comment by mlwoodward** [comment] 2014-11-14 00:19
I am digging further into this issue.  Thomas and I reviewed it on Wednesday and believe we have tracked down the issue.  We are digging further into possible solutions.

**Comment by mlwoodward** [comment] 2014-11-14 18:39
**Migrated from issue #179**

**Aug 29:** From Client
Noticed search bars require full text and won’t accept a minimum or partial text (E.g. three characters of a word). Could be a problem down the road and seems to conflict with claim of “Robust and stronger search engine optimization”. They will remove the restrictive parameters – but more descriptive content used for search is always best. Ray said to please remove parameters. Still does not seem to find all results when using three characters. Seems to require complete words.

**Aug 29:** Found out that this is for the search on http://ccctransfer.org/school-search and not on the top of the page. Will research.

**Sept 15:** The searches are now working, however found that the issue is now partial word searches. Looking into a module patch and testing.

Closing that issue as they are now merged together.

**Comment by Ruth-DeTro** [comment] 2014-11-14 19:03
Thank you. ☺

**Comment by mlwoodward** [comment] 2015-04-10 00:00
Closed until next fiscal year at the request of Ray.

**Closed as completed by mlwoodward** 2015-04-10 00:00 UTC
Labels: enhancement, help wanted, question, development

**Comment by Ruth-DeTro** [comment] 2015-04-10 15:49
Thanks Michael,

We will revisit this issue in the future.
